Repository SAP-Academy-Engineering/bb-reviews-starter, pull requests merged in 2019-10, with the labels that each got.

#21 Fix problem about hdi deploy not exiting
  db/package.json
Labels: enhancement

#25 Implement feature toggle module on server-side
  app/webapp/controller/BaseController.js
  app/webapp/controller/CreateReview.controller.js
  app/webapp/index.html
  app/webapp/view/Reviews.view.xml
  srv/config/FeatureToggles.js
  srv/routes/reviews.js
  srv/utils/FeatureToggleUtils.js
Labels: team_7_tars

#30 add database retrieval cache
  srv/server/hana-reviews-service.js
  srv/utils/dbPromises.js
Labels: team_8_fantastic_four
